services:
  db-dev:
    image: postgres:16-alpine
    container_name: cementery-db-dev
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: DB_Cementerio
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: